### ISSUE TITLE
To Endeavour to incorporate "lombok" with Neptune.

### ISSUE THREAD

**Issue by ArisAgnew** [TinkoffCreditSystems/neptune#123]
- Implement;
- Implemented functionality is about to be covered up by unit tests. 

P.S. You have to see in which modules/assemblies you may apply the framework "lombok".

**Comment by ArisAgnew** [comment]
@TikhomirovSergey Hey, If you have some more remarks about that task, please enlighten me as to it.

**Comment by TikhomirovSergey** [comment]
@ArisAgnew :+1: 
Could you explain what to you want to achieve?
Also could you show the example of such mapping?
I think it is possible to use lombok with datanucleous
